# we can set active profile from here as well no need to pass at run time
# but can't use this for config client don't know why
#spring:
#  profiles:
#    active:
#    - test
#    - actuator
#    - default
#  main:
#    banner-mode: "off"
# info property details shows in actuators info url http://localhost:8760/actuator/info
info:
  name: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'
  id: cfg
  artifactId: '@project.artifactId@'
  packaging: '@project.packaging@'
  groupId: '@project.groupId@'
  
message: local yml  
# below properties will override the bootstarp yml properties
#server:
#  port: 8705

# It will not work , you need to put in bootstrap yml
#spring:
#  cloud:
#    config:
#      uri: http://localhost:8701
---
spring:  profiles: test
message: local test 

---
spring:
  profiles: int
message: local int 